baseURL = "/"
languageCode = "en-ca"
title = "Kirby Kevinson 🌆"
theme = "14292"

paginate = 12

[params]
timeDilation = true
mediaUrl = "https://kirby.kevinson.org/"

[markup.goldmark.renderer]
unsafe = true
