name = "1997"
license = "MIT"
licenselink = "https://gitlab.com/kirbykevinson/website/-/blob/master/themes/1997/LICENSE"
description = "A blast from the past"
homepage = "https://kirby.kevinson.org/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Kirby Kevinson"
  homepage = "https://kirby.kevinson.org/"
