name = "14292"
license = "0BSD"
#licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A theme, I guess?"
#homepage = "http://example.com/"
#tags = []
#features = []
min_version = "0.41"

[author]
  name = "Kirby Kevinson"
  homepage = "https://kirbykevinson.gitlab.io/"
